---
title: "2020 Pre-E2M2 Research Workshop"
---

**Friday, Jan 3 - Sunday, Jan 5: Mentor Pre-Research Workshop** 
*(at [Institut Pasteur de Madagascar](http://www.pasteur.mg/) in Antananarivo)*

**Friday, Jan 3**

* 8:30-9:00am: Introductions and expectations (**Cara**)
* 9:00-10:30am: Former mentor research updates and feedback
  * Each mentor will give a 15 minute powerpoint presentation on their research progress in the past     year. Please use the last slide of your presentation to outline any:
    (1) roadblocks to your research progress 
    (2) needs from the E^2^M^2^ instructors that would help you progress
* 10:30-11:00am: Coffee break
* 11:00am - 12:30pm: One-on-one instructor meetings to set agenda for the pre-workshop
  * **Antso** meets with **Cara**
  * **Soa Fy** meets with **Sarah**
  * **Mirana** meets with **Tanjona**
  * **Fara/Jean-Marius** meet with **Andres**
* 12:30 - 1:30pm: Lunch
* 1:30 - 2:30pm: E^2^M^2^ 2020 mentors arrive to be briefed on their teaching roles for the rest of the workshop.
* 2:30 - 5:00pm: Individual former mentor-instructor groups work independently and make progress as needed
* 2:30 - 5:00pm: R Bootcamp instructors (Fidy and Christian...and Fara?) brief new mentors on their expectations for helping during the Bootcamp and the workshop

**Saturday, Jan 4** 

* 9:00am - 5:00pm: Independent one-on-one work time between instructors and former mentors
* Coffee and lunch will be provided throughout the day.

**Sunday, Jan 5** 

* 8:30am - 3:00pm: Independent one-on-one work time between instructors and former mentors
* 3:00 - 4:00pm: Former mentors give informal, 10 minute 'chalk talk' updates about the past two days of progress. The group brainstorms more effective approaches together.
* 4:00 - 5:00pm: All instructors available for any last-minute questions.
* Coffee and lunch will be provided throughout the day.

**Monday, Jan 13** 

* 8:30am - 5:00pm: A subset of instructors will meet with mentors about progress from the previous week.
* Coffee and lunch will be provided throughout the day.

**Tuesday, Jan 14** 

* 8:30am - 5:00pm: Mini-Symposium.
  * Would any former mentor like to volunteer to give a 15-minute research presentation to IPM (in French)?
  