---
title: "2019 Syllabus"
---

Please follow instructions for installing packages in R [here](E2M2-2018/E2M2_InstallPackages.html).

Find your 'Challenge and Mentoring' Teams for the week [here](E2M2-2019/Admin/ChallengeandMentoringTeams.html).


**Saturday, Jan 12: ‘R Bootcamp’ (attendance optional)** *(at [Institut Pasteur de Madagascar](http://www.pasteur.mg/) in Antananarivo)*

* 8:00-8:30am: Brief Introductions __(Cara)__
* 8:30-10:00am: [Intro to R Studio](E2M2-2019/1_Bootcamp_Rbasics.zip) __(Fidy)__
    * Knowing your working environment
    * Assigning variables
    * Basic arithmetic
    * Running a script
* 10:00-10:30am: Coffee Break
* 10:30am-12:00pm:  Small Groups: Software installation and catch-up. Mentors + instructors make sure all students have the proper materials installed and work through [4 tutorials](E2M2-2018/E2M2_R_tutorials.zip) with them. __(Mentors)__
* 12:00-1:00pm: Lunch
* 1:00-3:00pm: Lecture/Tutorial: [Exploring & visualizing data in R](E2M2-2019/1_Bootcamp_ExplorationVisualizationR.zip) __(Christian)__
* 3:00-3:30pm: Coffee Break
* 3:30-4:30pm: Lecture/Tutorial: [Writing For-loops, If-Else Statements, and Functions in R](E2M2-2019/1_Bootcamp_Functions&ForLoops.zip) __(Cara)__
* 4:30-5:30pm: Open mentoring session for outstanding questions

**Sunday, Jan 13: “Travel Day"**

* 6:00am: Meet at Institut Pasteur for departure to Ranomafana (lunch stop Antsirabe)
* 6:30-7:30pm: Dinner
* 7:30-8:30pm: Introductions __(Cara)__ and [Ice Breakers](E2M2-2019/IceBreaker/IceBreaker.pdf) with [data](E2M2-2019/IceBreaker/ice_breaker_day1_challenge_data_set.csv) __(Ben)__

**Monday, Jan 14 “Dealing with Data”**

* 6:30-8:00am: Breakfast
* 8:00-8:30am: Road Map and Daily Agenda __(Cara)__
* 8:30-10:00am: Lecture: [What are We Doing Here? Data and Models](E2M2-2019/2_E2M2_2019_Models_and_Data.pdf) __(Cara)__
* 10:00-10:30am: Coffee Break
* 10:30-11:45am: Introductions: 2-min student/mentor/instructor introductions and mentor research presentations __(Amy)__
* 11:45am-12:00pm: [Preparation for Women's March Madagascar](E2M2-2019/Homework_Submissions/2019-slide_submissions/instructor_mentors/WomensMarchPrez.pptx)  __(Liz)__
  * Click [here](E2M2-2019/WhyDoIMarch.html) for discussion points about the Women's March!
* 12:00-1:00pm: Lunch
* 1:00-2:00pm: [Lecture: Linear regression and simple statistics](E2M2-2019/2_BasicStatisticalModels.zip) __(Andres)__
* 2:00-3:00pm: Tutorial: Basic statistical modeling in R __(Andres)__
* 3:00-3:30pm: Coffee Break
* 3:30-5:00pm: Writing Exercise: Formulating Research Questions ([HW](E2M2-2019/2_HW_Formulating_Research_Questions.pdf)) __(Cara)__
* 5:00-5:30pm: [Beginning Malagasy Lesson](E2M2-2019/2-E2M2-2019-Malagasy-Lesson.pdf) __(Mentors)__
* 5:30-6:30pm: Free time, or one-on-one mentoring 
* 6:30-7:30pm: Dinner

**Tuesday, Jan 15: “Deeper Thinking With Data”**

* 6:30-8:00am: Breakfast
* 8:00-8:15am: Road Map and Daily Agenda __(Cara)__
* 8:15-10:00am: Lecture/Tutorial: Introduction to Mixed Modeling __(Andres)__
* 10:00-10:30am: Coffee Break; prep for hike
* 10:30am-1pm: Morning hike in Ranomafana National Park
* 1:00-1:45pm: Lunch
* 1:45-3:00pm: Exercise + Discussion: [Dynamical Fever](E2M2-2019/3_Dynamical_Fever.zip) __(Mentors + Christian)__
* 3:00-4:00pm: Lecture: [Study Design and Data Collection/Management](E2M2-2019/3_EpiStudyDesign.zip) __(Amy/Ben)__
* 4:00-4:30pm: Coffee Break 
* 4:30-5:30pm: Group exercise: Refining research questions for modeling ([HW](E2M2-2019/2_HW_Formulating_Research_Questions2.pdf)) __(Cara)__
* 5:30-6:30pm: Free time, or one-on-one mentoring, or additional time for Tutorial: Mixed Modeling in R
* 6:30-7:30pm: Dinner


**Wednesday, Jan 16: “Thinking About Mechanism”**

* 6:30-8:00am: Breakfast
* 8:00-8:15am: Road Map and Daily Agenda __(Cara)__
* 8:15-10:30am: [Lecture/Tutorial: Introduction to Compartmental Models and Differential Equations](E2M2-2019/4_IntroCompartmentalModels.zip) __(Amy)__
* 10:30-11:00am: Coffee Break
* 11:00am-11:30pm: Writing Exercise: Creating a model world to address a research question ([HW for tomorrow](E2M2-2019/4_Model_Framework_HW.pdf)) __(Cara)__
* 11:30am-12:00pm: [Small Group Session](E2M2-2019/Small_Group_Assignments.pdf): Refining research questions for modeling  __(all instructors lead small groups)__
* 12:00-1:00pm: Lunch
* 1:00-2:00pm: Small Group Session: Refining research questions for modeling (cont.) __(all instructors lead small groups)__
* 2:00-3:00pm: [Small Group Discussion: Reading Keeling and Gilligan]((E2M2-2018/E2M2_Readings.zip)) __(Mentors + Sarah)__
* 3:00-3:30pm: Coffee Break
* 3:30-4:45pm: [Lecture w/Tutorial: Introduction to Occupancy Modeling](E2M2-2019/4_Occupancy_2019.zip) __(Fidy)__
* 4:45-5:00pm: [Additional Preparation for the Women's March Madagascar](E2M2-2019/4_FanazavaniWomensMarch.pdf) __(Liz)__
* 4:45-5:45pm: Mid-session feedback. __(Mentors)__
* 6:00-6:40pm: Free time, or one-on-one mentoring
* 6:30-7:30pm: Dinner


**Thursday, Jan 17: “Fitting Models to Data”**

* 6:30-8:00am: Breakfast
* 8:00-8:15am: Road Map and Daily Agenda __(Cara)__
* 8:15-9:45am: Lecture w/Tutorial: Model Fitting in Practice – the Basic Concept __(Sarah)__
* 9:45-10:30am: Exercise: Epidemics Cards __(Mentors + Sarah)__
* 10:30-11:00am: Coffee Break
* 11:00-12:00pm:  Tutorial: Model Fitting with Epidemic Cards __(Mentors + Sarah)__
* 12:00-1:00pm: Lunch
* 1:00-2:00pm: Lecture/Tutorial: Introduction to Spatial Modeling __(Ben)__
* 2:00-3:30pm: Model Telephone with Model Diagrams __(Mentors + Christian)__
* 3:30-4:00pm: Coffee Break
* 4:00-4:15pm: Final research plans (HW) __(Cara)__ 
* 4:15-6:30pm:  Free time, or one-on-one mentoring
* 6:30-7:30pm: Dinner
* 8:00pm: Night walk Ranomafana National Park (optional)


**Friday, Jan 18: “Refining Your Work”**

* 6:30-8:00am: Breakfast
* 8:00-8:30am: Road Map and Daily Agenda __(Cara)__
* 8:30-10:00am: Lecture/Tutorial: Model Selection and Comparison __(Cara)__
* 10:00-10:30am: Coffee Break
* 10:30-12:00pm:  Lecture w/Tutorial: Introduction to Network Modeling __(Fidy)__
* 12:00pm-1:00pm: Lunch
* 1:00-1:30pm: Group photo - Wear your E2M2 shirts!
* 1:30-3:30pm: Lecture/Tutorial: Modeling Vector-Borne Disease __(Amy/Ben)__
* 3:30-4:00pm: Coffee Break
* 4:00-5:00pm: Mentor research presentations (10 min each) __(Mentors)__
* 5:00-6:30pm: Work time + student-instructor meetings __(all)__
* 6:30-7:30pm: Dinner



**Saturday, Jan 19: “Putting It All In Perspective”**

* 6:30-8:00am: Breakfast
* 8:00-8:15am: Road Map and Daily Agenda __(Cara)__
* 8:15-9:15am: Lecture: Modeling in Practice: The Life Cycle of a Modeling Project, from Conception to Publication __(Andres)__  
* 9:15-9:45am: Research Snapshots __(instructors)__
* 9:45-10:15am: Coffee Break
* 10:15-11:15am: Lecture: Looking back: How far have we come? __(Fidy)__
* 11:15am-12:00pm: Student presentation preactice
* 12:00-1:00pm: Lunch
* 1:00-6:30pm: Women’s March Madagascar (optional), March will proceed from CVB to Ranomafana town. Speakers and activities for all who are interested. __(Liz)__
* 6:30-9:00pm: Farewell dinner in Ranomafana town (Hotel Manja)
* 9:30pm: Return bus to CVB

**Sunday, Jan 20: (Travel Day)**

* 5:00-6:00am: Breakfast to go
* 6:00am: Board bus
* Return to Antananarivo 

**Monday, January 21: "Sharing Your Work"** *(at [Institut Pasteur de Madagascar](http://www.pasteur.mg/) in Antananarivo)*

* 9:00-11:00am: Closing ceremony and final student presentations __(Cara)__
* 11:00am-12:00pm: Final Feedback Session __(Julio + Mentors)__
* 12:30-2:00pm: Farewell lunch
* 2:00-4:30pm: Mini-symposium: **“Modeling Insights Into Epidemiology and Ecology”** *(Instructor presentations)*
    * Instructor and mentor research presentations, (TBA, 5-10 min each + questions) 
* 4:30pm: Social Hour
